### ISSUE TITLE
Create a Calculator using c language

### ISSUE THREAD

**Issue by krishnapatidar458** [krishnapatidar458/hacktoberfest2023#11]
source to code:- https://github.com/krishnapatidar458/hacktoberfest2023/blob/main/c/Calculator.c

**Comment by shishirkj** [comment]
if not assigned can i work on this?

**Comment by krishnapatidar458** [comment]
@shishirkj yes but i can't able to merge your pull request

**Comment by shishirkj** [comment]
can i ask why ?

**Comment by ombhagwat2401** [comment]
Hello @krishnapatidar458, Can I work on this ?

**Comment by krishnapatidar458** [comment]
@shishirkj ok

**Comment by RealCifer** [comment]
Hello @krishnapatidar458 hope you are doing well. I want to contribute in this issue and solve it for you. Can u assign me this issue?

**Comment by mansidhote** [comment]
Hey @krishnapatidar458 , Can you please assign it to me under hacktoberfest2023 label.
