### ISSUE TITLE
Implement Palindrome program in C language

### ISSUE THREAD

**Issue by krishnapatidar458** [krishnapatidar458/hacktoberfest2023#6]
Create a program that takes a palindrome string and displays whether it is a palindrome or not.

Code in: https://github.com/krishnapatidar458/hacktoberfest2023/blob/main/c/palindrome.c

**Comment by yashj09** [comment]
hi i am having this error while pushing the code pls help me
remote: Permission to krishnapatidar458/hacktoberfest2023.git denied to yashj09.
fatal: unable to access 'https://github.com/krishnapatidar458/hacktoberfest2023.git/': The requested URL returned error: 403

**Comment by krishnapatidar458** [comment]
@yashj09 it is all right from my side.

**Comment by mansidhote** [comment]
Hey @krishnapatidar458, Can you please assign it to me under hacktoberfest2023 label.
