### ISSUE TITLE
Implement Huffman Algorithm program in python 

### ISSUE THREAD

**Issue by krishnapatidar458** [krishnapatidar458/hacktoberfest2023#8]
code in:https://github.com/krishnapatidar458/hacktoberfest2023/blob/main/python/Huffman_Algorithm.py

**Comment by Tejoooo** [comment]
Heyy @krishnapatidar458  I m interested to work on this can u assign me this issue

**Comment by krishnapatidar458** [comment]
@Tejoooo  yes you can

**Comment by Tejoooo** [comment]
@krishnapatidar458 can u add the hacktoberfest-accepted label

**Comment by krishnapatidar458** [comment]
I already added

**Comment by RealCifer** [comment]
Hello @krishnapatidar458  hope you are doing well. I want to contribute in this issue and solve it for you. Can u assign me this issue?
